name: Create incident

on:
  issues:
    types: [opened]

permissions:
  contents: write

jobs:
  create-incident:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/setup
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create incident
        run: |
          node src/index.mjs incident create ${{ github.event.issue.number }} \
            --title "${{ github.event.issue.title }}" \
            --text "${{ github.event.issue.body }}"

      - run: ls -Rla
      - run: git status

      - name: Commit changes
        run: |
          git add .
          git commit -m "Create incident #${{ github.event.issue.number }}"
          git push
